name: foxgpt_native
description: Native C++ engine bridge for FoxGPT.
publish_to: none
version: 0.3.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  code_assets: ^2.0.0
  ffi: ^2.2.0
  hooks: ^2.2.0
  logging: ^1.3.0
  native_toolchain_c: ^0.19.4
  native_toolchain_cmake: ^0.3.2
